### ISSUE TITLE
First command execute when running the shell fails.

### ISSUE THREAD

**Issue by alexs10** [JoshNassar94/COP4600_Project#14]
Something about error in user_created_commands.c: bad filename

**Comment by JoshNassar94** [comment]
That's really weird. Have you done enough testing to say for sure it's only ever the first one?

**Comment by JoshNassar94** [comment]
Kind of a hacky fix, but I set a flag to check if it was the first command and didn't call resolve_errors if it was. So, technically not good. But works for now...

**Comment by JoshNassar94** [comment]
Fixed with the new way we're handling input.
