### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by alexs10** [JoshNassar94/COP4600_Project#15]
If the first command is piped, it does not execute. Doing the same command again does work though.

```
ls -l | wc
```

```
alias a "ls -l"
alias b wc
a | b
```

EDIT: fixed this one

**Comment by alexs10** [comment]
Statements with 4 or more commands do not execute

```
ls | wc | wc | wc
```

**Comment by JoshNassar94** [comment]
Hmm...no clue what the issue is with either of those things. I never did anything with the piping commands, and it seems as if that's where the issue is. Would be great if it could be fixed, but still seems kinda minor.

**Comment by alexs10** [comment]
I think I may have messed up a little on piping. I will work on it.

**Comment by alexs10** [comment]
Fixed everything. Kinda. I got rid of free linked list in default and all these problems go away.
