### ISSUE TITLE
Some commands typed wrong will freeze the shell

### ISSUE THREAD

**Issue by alexs10** [JoshNassar94/COP4600_Project#16]
Typing

```
wc
```

will prevent any further commands from being type. This is because the normal exit char  will exit the whole shell. Any way to fix this or is this ok?

**Comment by JoshNassar94** [comment]
That's actually what the normal shell does, believe it or not...I think I'll just put a check for that and have it send an error. Cuz we need a way to get out of it.

**Comment by JoshNassar94** [comment]
Fixed this by checking if wc is called with no args. Prints an error message if so.
