### ISSUE TITLE
WC no arg is really hacky

### ISSUE THREAD

**Issue by alexs10** [JoshNassar94/COP4600_Project#18]
Their are a lot of commands like that which will freeze the shell. Maybe we should just make something an escape character. Or ignore the issue. Stuff like "sort" also behaves the same.

**Comment by JoshNassar94** [comment]
Oh, it's definitely super hacky. The thing is, they all do that on the normal shell too. So either we ignore it or we make an escape character.

**Comment by JoshNassar94** [comment]
Actually, problem solved. After a bit of searching, CTRL-D will actually break you out of it. You can even preface it with a file name and it will read that file. For example:

```
/home/josh/school/cop4600/cop4600_project/use_this$ wc
out.txt
<CTRL-D>
      1       1       8
/home/josh/school/cop4600/cop4600_project/use_this$ 
```

Meaning, this behavior is completely correct.
