### ISSUE TITLE
Submitting

### ISSUE THREAD

**Issue by JoshNassar94** [JoshNassar94/COP4600_Project#19]
I won't be able to work on this at all tomorrow, I've got stuff all day. I'll try to get anything else done tonight that I can, but no promises. I'm still up for submitting it, just make sure any commits you have are in by like 10ish to give me time to organize the files and make sure it submits nicely in time. And let me know when your final change is in so I'm not waiting.

**Comment by alexs10** [comment]
Well I tried to fix the aliasing/piping issue. Lots of funky things happening. So I think we can just submit it as is.

**Comment by alexs10** [comment]
Do you remember the time we are meeting with the TA tomorrow?

**Comment by JoshNassar94** [comment]
That's exactly how I felt about the wildcard matching and file name completion. I think we got a good amount done anyways. I'm working on cleaning up files and going to submit by 11:00 most likely. We meet at 12:20.

**Comment by JoshNassar94** [comment]
Also, @alexs10 it doesn't really like executing from a file...
All the output is funky, like it puts all of our print statements (such as current path, printed aliases, etc) in a giant stack at the bottom. It's not really correct...
Try creating a text file with some commands, then run `./shell < test.txt`
It's super funky

**Comment by alexs10** [comment]
Ya i see that too.

**Comment by JoshNassar94** [comment]
Do you have any idea whatsoever on how to fix that? Or even what the issue is? It almost seems like it's just forking processes really strangely, I don't really understand it

**Comment by alexs10** [comment]
Well I could not solve it in the last ten minutes. So I think I will put it in the readme. Its still works correctly. It just prints weird. Even if we did fix it it would still not be able to print all the commands entered in the file.

**Comment by JoshNassar94** [comment]
Yeah, I kinda agree. I can't believe we didn't catch that sooner. I have no clue why that is happening to be honest, or how to even begin to fix it. And at least we get to talk through it a bit with the TA's. Also, is that last commit of commenting out the free linked list thing necessary?

**Comment by JoshNassar94** [comment]
Never mind, I just did another pull and got it regardless. I was just wondering if it would break anything.

**Comment by alexs10** [comment]
Ya. If we free the linked list a bunch of pipes dont work. The memory leak is better. I took away the linked list thing for the nonbackgroung commands earlier but I missed the background ones.

**Comment by JoshNassar94** [comment]
Ok, sounds good. I cleaned things up a little bit for the final submission (got rid of the data_structures folder, just put the stuff in dev), and updated the readme a tiny bit. I'm gonna push it real quick, look it over for a minute and let me know if it's good to submit.

**Comment by JoshNassar94** [comment]
I'm planning on submitting the whole folder called shell_project. Just pushed it. Let me know in like the next 5 minutes

**Comment by alexs10** [comment]
Sounds good to me.

**Comment by JoshNassar94** [comment]
Submitted.
