### ISSUE TITLE
File redirection

### ISSUE THREAD

**Issue by JoshNassar94** [JoshNassar94/COP4600_Project#3]
Can you provide what you're testing the input redirection with? I can't seem to get it to work...

**Comment by alexs10** [comment]
ls > "filename"
ls >> "filename"
wc < "filename"
wc -l <"filename"

**Comment by alexs10** [comment]
What were you trying?

**Comment by alexs10** [comment]
also 

wc < "filename" > "filename" works too.

**Comment by JoshNassar94** [comment]
Looks great. Except when I just do ls < "filename" all I get are the printed results of running "make"....
It works with ls -l though, I don't really understand

**Comment by alexs10** [comment]
I do not get that. That is fairly weird.
