### ISSUE TITLE
Aliasing is broken...

### ISSUE THREAD

**Issue by JoshNassar94** [JoshNassar94/COP4600_Project#4]
Aliases used to work correctly, I think something that you changed while working on piping broke it.

**Comment by alexs10** [comment]
Um... crap. My bad. Can you give me some test cases.

**Comment by JoshNassar94** [comment]
Just even anything simple such as:

alias a ls
a

alias b "ls -l"
b

**Comment by alexs10** [comment]
making sure. The error you are getting is endlessly writing the dir to the page right?

**Comment by alexs10** [comment]
I will try to fix this tomorrow. Was this working before the commits today? As in when you were doing wildcards, aliasing was still working?

**Comment by JoshNassar94** [comment]
That is the error I'm getting, yes. And I just double checked everything, it's in your last commit, you took out all the "exit(0)" lines after execute_external_command is called. I just put them back in, and everything seems to work fine. Committing it, let me know if those were taken out for an important reason.

**Comment by alexs10** [comment]
Ok so I took those away because the call execvp in execute_external_commands ends the process. So that should never get called. So some magic or something inside of the alias code.

Also the alias does not work for all recursive situations. Alias work when you put them in pipes, like

```
alias a "ls -l"
alias b wc
a | b
```

But the following does will not work.

```
alias c "a | b"
alias b "a > testfile"
```

**Comment by JoshNassar94** [comment]
Well the thing is, we're using execve (not allowed to use execvp), and I don't see any exit calls in execute_external_commands. Idk.

I just tried all of those. It seems like the issue is that it won't let you create more than two aliases.
`alias b "a > testfile.txt"` seems to work fine. I'll have to check on that later.

**Comment by JoshNassar94** [comment]
Fixed the issue and pushed. Closing this issue.
