### ISSUE TITLE
Task: Ampersand

### ISSUE THREAD

**Issue by JoshNassar94** [JoshNassar94/COP4600_Project#6]
Implement ampersand for commands to run in the background.

**Comment by JoshNassar94** [comment]
Working on this

**Comment by JoshNassar94** [comment]
I'm not sure what all needs to work with background processing. Things like setenv, alias word word, unsetenv actually change things about the state. Should the background processes be able to change things in the parent process? Because I know cd doesn't. Left those alone for now, gonna email the prof and see.

**Comment by alexs10** [comment]
?Lots of things like ampersand are not supposed to execute with built in commands.

**Comment by JoshNassar94** [comment]
Are you sure? On a normal shell they don't fail, they just don't really do anything. Which is what ours does currently...

**Comment by JoshNassar94** [comment]
I emailed Helal about it, he confirmed that built-ins cannot run in the background. Just gotta handle it with error checking, which really just means I need to put some print statements in the things I've already sectioned off. Will do that tonight.
